name: Build Add-In
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2  

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet Packages
      run: nuget restore FullMonty.sln

    - name: Build Sln
      run: msbuild FullMonty.sln /p:Configuration=Release

    - name: Run Tests
      run: packages/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe FullMonty.UnitTests/bin/Release/FullMonty.UnitTests.dll

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: xl_addin
        path: |
          FullMonty.AddIn/bin/Release/FullMonty.AddIn-AddIn64-packed.xll
          FullMonty.AddIn/bin/Release/FullMonty.AddIn-AddIn-packed.xll

  release-please:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple